components/TopicBrowser.vue
=> init selected topics

assets_to_JSON.py, components/CoverImageBrowser.vue, components/TopicBrowser.vue, data/cover-images.json
dependency: #19 
> 讀檔的python還要再修～～～
=> read assets in common assets and write to a json file

components/BetterLongForm.vue
1. 支援「不算分數，只顯示選擇結果」
2. 可將結果更新至 shareURL
=> BetterLongForm 支援 selection

components/interactive/Faq.vue
=> faq component adjust

components/interactive/Faq.vue, components/map/DefenseMap.vue, components/modal/Message.vue
remove custom link tag
標示點點增加動畫
調整點點顏色
增加 hover 上去後 變成不透明
移除連結區純文字
將文字加在連結上
=> civil defense adjust

components/comp/Infobox.vue
讓 Infobox 可以顯示超過兩行的 ghost document
1. Remove maxSectionNum
2. Use Computed instead of mixing v-if and v-for, which is recommended by Vue.js Official
=> Remove restriction of section number = 2

lib/core.js
這個是舊的定期定額 + 註冊流程用的，更新之後已經不會再用到
=> Remove unused core api

components/GenderSlider.vue
修改範圍:
1. 調整文字顯示，原本只有單一文字，變成  **%男 **%女 
1. 當數值為0時，是否要顯示 50% 男 50% 女
=> feat: adjust gender slider

interfaces/knowsAuth.js
https://trello.com/c/UMvFXroQ/30-%E7%A7%BB%E9%99%A4%E5%AD%98%E5%9C%A8-localstorage-%E8%A3%A1%E7%9A%84-watchout-handle
=> Remove watchout-handle at knowAuth

components/Login.vue, interfaces/knowsAuth.js
=> Remove handle when sign out

components/ghost/AfterArticle.vue
=> remove share text

components/ReferencePreview.vue
=> feat: remove avatar link

components/comp/DocHeader.vue
=> set link is false

components/comp/Collection.vue
collection component add class name
=> feat: collection component add class name

components/modal/Reminder.vue, components/modal/index.js
=> feat: add remind popup component

lib/firestore.js
=> feat: add firestore bunko getAuthors

components/NavBar.vue
=> feat: add member name in nav bar

lib/firestore.js
=> feat: add firestore.bunko.getAuthors

components/NavBar.vue
=> fix: adjust nav bar name

components/Icon.vue
調整 icon component
icon component 增加 faThumbtack icon
=> feat: adjust icon component

lib/firestore.js
=> feat: add firebase api

lib/core.js
=> feat: add delete persona role api

lib/firestore.js
支援記者個人頁面需求，可用作者 id 在 firestore query 文章
=> Firestore: get docs by author id

lib/core.js, lib/firestore.js
增加 author id page API
調整 firebase 使用 get persona by id Api name
調整 core get persona by id Api
新增 persona id Api
=> feat: add author api

components/button/Submit.vue
在 submit button 上增加一個 disabled prop，可以直接讓按鈕 disable，也讓樣式變 disabled
=> Add disabled state for submit button

components/comp/DocHeader.vue
文章頁面，只有仍然合作中的作者會有連結，所以需要調整 visibility
=> Config the visibility of author link

components/Login.vue
=> feat: add error messgae in login component

components/Login.vue
Reverts watchout-tw/watchout-common-functions#166
=> Revert "feat: add error messgae in login component"

components/Login.vue, components/button/Submit.vue, interfaces/knowsError.js, lib/errors.js
=> feat: login component add error message
